# 🔢 NumPy (Numerical Python)

**NumPy** is the fundamental open-source library for scientific computing in Python.

It provides:
- ✔ Fast N-dimensional arrays  
- ✔ Powerful mathematical functions  
- ✔ High-performance numerical operations  

NumPy is widely used in:
- 📊 Data Science  
- 🤖 Machine Learning  
- 📈 Data Analysis  
- 🔬 Scientific Computing  

---

# 📌 Importing NumPy

```python
import numpy as np

<table style="width:85%; font-size:14px; border-collapse:collapse; margin:auto;"> <thead> <tr style="background-color:#f2f2f2;"> <th style="color:purple; border:1px solid #333; padding:10px;">Feature</th> <th style="color:purple; border:1px solid #333; padding:10px;">Description</th> </tr> </thead> <tbody> <tr> <td style="border:1px solid #333; padding:8px;"><b>ndarray Object</b></td> <td style="border:1px solid #333; padding:8px;"> Fast multidimensional array structure </td> </tr> <tr> <td style="border:1px solid #333; padding:8px;"><b>High Performance</b></td> <td style="border:1px solid #333; padding:8px;"> Much faster than Python lists </td> </tr> <tr> <td style="border:1px solid #333; padding:8px;"><b>Broadcasting</b></td> <td style="border:1px solid #333; padding:8px;"> Performs operations on arrays of different shapes </td> </tr> <tr> <td style="border:1px solid #333; padding:8px;"><b>Mathematical Functions</b></td> <td style="border:1px solid #333; padding:8px;"> Includes algebra, statistics, and random tools </td> </tr> </tbody> </table>

<table style="width:80%; font-size:14px; border-collapse:collapse; margin:auto; text-align:center;"> <thead> <tr style="background-color:#f2f2f2;"> <th style="color:purple; border:1px solid #333; padding:10px;">Function</th> <th style="color:purple; border:1px solid #333; padding:10px;">Purpose</th> </tr> </thead> <tbody> <tr> <td style="border:1px solid #333; padding:8px;">np.array()</td> <td style="border:1px solid #333; padding:8px;">Creates array</td> </tr> <tr> <td style="border:1px solid #333; padding:8px;">np.zeros()</td> <td style="border:1px solid #333; padding:8px;">Array filled with zeros</td> </tr> <tr> <td style="border:1px solid #333; padding:8px;">np.ones()</td> <td style="border:1px solid #333; padding:8px;">Array filled with ones</td> </tr> <tr> <td style="border:1px solid #333; padding:8px;">np.arange()</td> <td style="border:1px solid #333; padding:8px;">Creates sequence of numbers</td> </tr> <tr> <td style="border:1px solid #333; padding:8px;">np.linspace()</td> <td style="border:1px solid #333; padding:8px;">Evenly spaced numbers</td> </tr> <tr> <td style="border:1px solid #333; padding:8px;">np.random.rand()</td> <td style="border:1px solid #333; padding:8px;">Random values</td> </tr> </tbody> </table>

Compared to Python lists:

<table style="width:80%; font-size:14px; border-collapse:collapse; margin:auto; text-align:center;"> <thead> <tr style="background-color:#f2f2f2;"> <th style="color:purple; border:1px solid #333; padding:10px;">Python Lists</th> <th style="color:purple; border:1px solid #333; padding:10px;">NumPy Arrays</th> </tr> </thead> <tbody> <tr> <td style="border:1px solid #333; padding:8px;">Slower</td> <td style="border:1px solid #333; padding:8px;">Faster</td> </tr> <tr> <td style="border:1px solid #333; padding:8px;">More memory usage</td> <td style="border:1px solid #333; padding:8px;">Memory efficient</td> </tr> <tr> <td style="border:1px solid #333; padding:8px;">Limited math operations</td> <td style="border:1px solid #333; padding:8px;">Advanced math support</td> </tr> </tbody> </table>

In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.5'

In [3]:
list = [0,1,2,3,4,5]

In [6]:
np_array = np.array(list)
print(np_array)
print(type(np_array))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
np.arange(10)                  # Arange 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [11]:
np.arange(10,20,30,2)

TypeError: Cannot interpret '2' as a data type

In [12]:
np.arange(20,10)              # In arange 1st argument always < 2nd arg

array([], dtype=int64)

In [13]:
np.zeros(3)                   # Float will be default

array([0., 0., 0.])

In [14]:
np.zeros(3,dtype=int)         # Hyper parameter tuning

array([0, 0, 0])

In [16]:
np.zeros([2,2])               # 2D array

array([[0., 0.],
       [0., 0.]])

In [17]:
np.zeros([2,2],dtype=int) 

array([[0, 0],
       [0, 0]])

In [18]:
np.zeros([10,10],dtype=int) 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
np.ones(4) 

array([1., 1., 1., 1.])

In [22]:
np.ones(4,dtype=int) 

array([1, 1, 1, 1])

In [23]:
np.two(3)

AttributeError: module 'numpy' has no attribute 'two'

In [29]:
np.random.rand(3)

array([0.05883143, 0.48060758, 0.56461401])

In [30]:
np.random.rand(3,4)

array([[0.25696656, 0.72448882, 0.66248808, 0.86367796],
       [0.74648965, 0.01479327, 0.93877123, 0.54942285],
       [0.25143142, 0.17591682, 0.99040122, 0.52164186]])

In [40]:
np.random.randint(3,4)

3

In [38]:
np.random.randint(3)

2

In [54]:
np.random.randint(10,20)

12

In [56]:
np.random.randint(10,20,4)    # last param number of items need to generate

array([10, 17, 15, 14])

In [59]:
m = np.random.randint(10,40,(10,10))

In [60]:
m

array([[24, 14, 26, 21, 20, 17, 35, 34, 27, 28],
       [33, 17, 24, 22, 13, 35, 24, 37, 11, 14],
       [10, 31, 24, 30, 36, 33, 39, 36, 34, 38],
       [38, 39, 13, 14, 17, 30, 27, 13, 29, 39],
       [28, 21, 29, 16, 17, 14, 25, 10, 33, 36],
       [31, 23, 28, 37, 39, 31, 38, 17, 24, 34],
       [14, 28, 23, 38, 33, 38, 13, 25, 11, 31],
       [20, 21, 21, 15, 35, 30, 15, 38, 18, 11],
       [28, 21, 19, 17, 34, 36, 23, 11, 34, 27],
       [18, 22, 29, 37, 14, 35, 25, 18, 39, 23]])

In [61]:
m.ndim

2

In [63]:
m.size

100

In [64]:
n = np.random.randint(10,40,(5,6))

In [65]:
n

array([[24, 10, 23, 13, 22, 21],
       [22, 25, 38, 33, 13, 38],
       [29, 17, 26, 20, 35, 28],
       [31, 25, 36, 14, 20, 25],
       [35, 19, 26, 11, 27, 30]])

In [67]:
#Array manupilation
n[0]
n[0] = [35, 45, 43, 32, 31, 65]

In [68]:
n

array([[35, 45, 43, 32, 31, 65],
       [22, 25, 38, 33, 13, 38],
       [29, 17, 26, 20, 35, 28],
       [31, 25, 36, 14, 20, 25],
       [35, 19, 26, 11, 27, 30]])

In [71]:
np.linspace(3,10,dtype=int)

array([ 3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,
        5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,
        7,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9, 10])

In [74]:
np.linspace(3,10,80,dtype=int)

array([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10])

In [76]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
np.linspace(3,10,80,endpoint=False, retstep=False,dtype=int)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [77]:
np.linspace(3,10,80,endpoint=True, retstep=False,dtype=int)   # Include last step

array([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10])

In [78]:
np.linspace(3,10,80,endpoint=True, retstep=True,dtype=int)   # Include last step

(array([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,
         4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,
         7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10]),
 np.float64(0.08860759493670886))

In [81]:
np.linspace(0,10,5,endpoint=True, retstep=True,dtype=int)    # The Retstep step size between elements  

(array([ 0,  2,  5,  7, 10]), np.float64(2.5))

In [5]:
n = np.random.randint(10,40,(2,3))
n

array([[33, 13, 24],
       [39, 30, 18]])

In [6]:
n[0]

array([33, 13, 24])

In [8]:
n[0,2]

np.int64(24)

In [9]:
n[0:2,1:3]

array([[13, 24],
       [30, 18]])

In [10]:
n[0:2,-1]

array([24, 18])

In [11]:
len (n)

2

In [12]:
n

array([[33, 13, 24],
       [39, 30, 18]])

In [16]:
m = n.reshape(3,2)

In [17]:
m

array([[33, 13],
       [24, 39],
       [30, 18]])

In [18]:
m.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

## Boolean masking & Filtering

# 🎭 Boolean Masking and Filtering in NumPy

Boolean masking is a technique used to filter or select elements from a NumPy array based on conditions.

It returns:
- ✔ `True` for matching elements  
- ✔ `False` for non-matching elements  

This is one of the most powerful features in NumPy for data analysis and machine learning.

---

# 📌 What is a Boolean Mask?

A Boolean mask is an array containing only:
- `True`
- `False`

These values are generated by applying conditions to arrays.

---

# 🔹 Example 1: Creating a Boolean Mask

```python id="m5q2xt"
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

mask = arr > 25

print(mask)

<table style="width:80%; font-size:14px; border-collapse:collapse; margin:auto;"> <thead> <tr style="background-color:#f2f2f2;"> <th style="color:purple; border:1px solid #333; padding:10px;">Advantage</th> <th style="color:purple; border:1px solid #333; padding:10px;">Benefit</th> </tr> </thead> <tbody> <tr> <td style="border:1px solid #333; padding:8px;">Fast Filtering</td> <td style="border:1px solid #333; padding:8px;"> Avoids loops </td> </tr> <tr> <td style="border:1px solid #333; padding:8px;">Readable Code</td> <td style="border:1px solid #333; padding:8px;"> Cleaner conditions </td> </tr> <tr> <td style="border:1px solid #333; padding:8px;">Efficient</td> <td style="border:1px solid #333; padding:8px;"> Optimized NumPy operations </td> </tr> </tbody> </table>

<table style="width:80%; font-size:14px; border-collapse:collapse; margin:auto; text-align:center;"> <thead> <tr style="background-color:#f2f2f2;"> <th style="color:purple; border:1px solid #333; padding:10px;">Operator</th> <th style="color:purple; border:1px solid #333; padding:10px;">Meaning</th> </tr> </thead> <tbody> <tr> <td style="border:1px solid #333; padding:8px;">&</td> <td style="border:1px solid #333; padding:8px;">AND</td> </tr> <tr> <td style="border:1px solid #333; padding:8px;">|</td> <td style="border:1px solid #333; padding:8px;">OR</td> </tr> <tr> <td style="border:1px solid #333; padding:8px;">~</td> <td style="border:1px solid #333; padding:8px;">NOT</td> </tr> </tbody> </table>

In [20]:
n = np.random.randint(10,40,(10,3))

In [21]:
n

array([[15, 18, 31],
       [32, 12, 20],
       [36, 10, 24],
       [36, 16, 25],
       [24, 12, 31],
       [28, 28, 31],
       [14, 29, 39],
       [20, 32, 18],
       [11, 12, 39],
       [37, 11, 32]])

In [22]:
n [ n > 20 ]

array([31, 32, 36, 24, 36, 25, 24, 31, 28, 28, 31, 29, 39, 32, 39, 37, 32])

In [23]:
n [ n < 20 ]

array([15, 18, 12, 10, 16, 12, 14, 18, 11, 12, 11])

In [36]:
n [ n == 20 ]

array([20, 20])

In [24]:
n [ n <= 20 ]

array([15, 18, 12, 20, 10, 16, 12, 14, 20, 18, 11, 12, 11])

In [25]:
n [ n >= 20 ]

array([31, 32, 20, 36, 24, 36, 25, 24, 31, 28, 28, 31, 29, 39, 20, 32, 39,
       37, 32])

In [27]:
n [ (n > 10) & (n < 30)]

array([15, 18, 12, 20, 24, 16, 25, 24, 12, 28, 28, 14, 29, 20, 18, 11, 12,
       11])

In [33]:
n [ (n < 20) | (n > 30) ]

array([15, 18, 31, 32, 12, 36, 10, 36, 16, 12, 31, 31, 14, 39, 32, 18, 11,
       12, 39, 37, 11, 32])

In [34]:
n [ (n !=20) ]

array([15, 18, 31, 32, 12, 36, 10, 24, 36, 16, 25, 24, 12, 31, 28, 28, 31,
       14, 29, 39, 32, 18, 11, 12, 39, 37, 11, 32])

In [38]:
n[ n % 2 == 0 ]

array([18, 32, 12, 20, 36, 10, 24, 36, 16, 24, 12, 28, 28, 14, 20, 32, 18,
       12, 32])

In [48]:
n[ n//2 > 10 ]

array([31, 32, 36, 24, 36, 25, 24, 31, 28, 28, 31, 29, 39, 32, 39, 37, 32])

In [49]:
n[ n//2 < 20 ]

array([15, 18, 31, 32, 12, 20, 36, 10, 24, 36, 16, 25, 24, 12, 31, 28, 28,
       31, 14, 29, 39, 20, 32, 18, 11, 12, 39, 37, 11, 32])

In [4]:
np.array([11,23,44] , dtype =float)

array([11., 23., 44.])

In [5]:
np.array([11,23,44] , dtype =bool)

array([ True,  True,  True])

In [6]:
np.array([11,23,44] , dtype =complex)

array([11.+0.j, 23.+0.j, 44.+0.j])

In [8]:
a1 = np.arange(10) # 1D
a1
a1.ndim

1

In [9]:
# indentity matrix is that diagonal items will be ones and evrything will be zeros
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
I = np.identity(3,dtype=int)
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Attributes

| Attribute  | Description                        | Example Output |
| ---------- | ---------------------------------- | -------------- |
| `shape`    | Dimensions of the array            | `(3, 4)`       |
| `ndim`     | Number of axes (dimensions)        | `2`            |
| `size`     | Total number of elements           | `12`           |
| `dtype`    | Data type of elements              | `float64`      |
| `itemsize` | Memory used by one element (bytes) | `8`            |
| `nbytes`   | Total memory used by array (bytes) | `96`           |


In [11]:
a1 = np.arange(10) # 1D
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a1.reshape(5,2)

In [19]:
a1.shape

(5, 2)

In [20]:
a1.ndim

2

In [21]:
a1.size

10

In [23]:
a1.itemsize

8

In [24]:
a1.dtype

dtype('int64')

In [25]:
a1.nbytes

80

## Changing Data Type

In [34]:
x = np.array([1,2,2.5])
x

array([1. , 2. , 2.5])

In [36]:
x = x.astype(int)
x

array([1, 2, 2])