# 📡 NumPy Broadcasting

Broadcasting is a powerful NumPy feature that allows arrays of different shapes to work together in mathematical operations.

Instead of manually repeating data, NumPy automatically expands arrays when possible.

---

# 🎯 Why Broadcasting?

Broadcasting helps:
- ✔ Reduce code complexity  
- ✔ Improve performance  
- ✔ Avoid unnecessary loops  
- ✔ Save memory  

---

# 📌 Basic Idea

NumPy automatically stretches smaller arrays to match larger arrays during element-wise operations.

---

# 🔹 Example 1: Scalar Broadcasting

```python id="m5q2xt"
import numpy as np

arr = np.array([1, 2, 3])

print(arr + 5)

🔹 Example 3: Compatible Shapes
<table style="width:70%; font-size:14px; border-collapse:collapse; margin:auto; text-align:center;"> <thead> <tr style="background-color:#f2f2f2;"> <th style="color:purple; border:1px solid #333; padding:10px;">Shape A</th> <th style="color:purple; border:1px solid #333; padding:10px;">Shape B</th> <th style="color:purple; border:1px solid #333; padding:10px;">Compatible?</th> </tr> </thead> <tbody> <tr> <td style="border:1px solid #333; padding:8px;">(3, 3)</td> <td style="border:1px solid #333; padding:8px;">(3, 3)</td> <td style="border:1px solid #333; padding:8px;">✔ Yes</td> </tr> <tr> <td style="border:1px solid #333; padding:8px;">(2, 3)</td> <td style="border:1px solid #333; padding:8px;">(3,)</td> <td style="border:1px solid #333; padding:8px;">✔ Yes</td> </tr> <tr> <td style="border:1px solid #333; padding:8px;">(4, 1)</td> <td style="border:1px solid #333; padding:8px;">(4, 5)</td> <td style="border:1px solid #333; padding:8px;">✔ Yes</td> </tr> <tr> <td style="border:1px solid #333; padding:8px;">(2, 3)</td> <td style="border:1px solid #333; padding:8px;">(2, 2)</td> <td style="border:1px solid #333; padding:8px;">❌ No</td> </tr> </tbody> </table>



<table style="width:90%; font-size:14px; border-collapse:collapse; margin:auto;"> <thead> <tr style="background-color:#f2f2f2;"> <th style="color:purple; border:1px solid #333; padding:10px;">Advantage</th> <th style="color:purple; border:1px solid #333; padding:10px;">Benefit</th> </tr> </thead> <tbody> <tr> <td style="border:1px solid #333; padding:8px;">Less Code</td> <td style="border:1px solid #333; padding:8px;"> Avoids manual loops </td> </tr> <tr> <td style="border:1px solid #333; padding:8px;">Fast Execution</td> <td style="border:1px solid #333; padding:8px;"> Uses optimized internal operations </td> </tr> <tr> <td style="border:1px solid #333; padding:8px;">Memory Efficient</td> <td style="border:1px solid #333; padding:8px;"> Avoids copying data </td> </tr> </tbody> </table>

1. Used in Vectorization
2. The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.
3. The smaller array is “broadcast” across the larger array so that they have compatible shapes.

Broadcasting Rules
1. Make the two arrays have the same number of dimensions.
If the numbers of dimensions of the two arrays are different, add new dimensions with size
1 to the head of the array with the smaller dimension.
ex : (3,2) = 2D , (3) =1D ---> Convert into (1,3)
(3,3,3) = 3D ,(3) = 1D ---> Convert into (1,1,3)
2. Make each dimension of the two arrays the same size.
If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are
stretched to the size of the other array.
ex : (3,3)=2D ,(3) =1D ---> CONVERTED (1,3) than strech to (3,3)
If there is a dimension whose size is not 1 in either of the two arrays, it cannot be
broadcasted, and an error is raised.
<table style="width:85%; font-size:14px; border-collapse:collapse; margin:auto; text-align:center;">
    <thead>
        <tr style="background-color:#f2f2f2;">
            <th style="color:purple; border:1px solid #333; padding:10px;">Rule</th>
            <th style="color:purple; border:1px solid #333; padding:10px;">Condition</th>
            <th style="color:purple; border:1px solid #333; padding:10px;">Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="border:1px solid #333; padding:8px;">Rule 1</td>
            <td style="border:1px solid #333; padding:8px;">Dimensions are equal</td>
            <td style="border:1px solid #333; padding:8px;">Broadcasting works</td>
        </tr>
        <tr>
            <td style="border:1px solid #333; padding:8px;">Rule 2</td>
            <td style="border:1px solid #333; padding:8px;">One dimension is 1</td>
            <td style="border:1px solid #333; padding:8px;">Dimension is expanded</td>
        </tr>
        <tr>
            <td style="border:1px solid #333; padding:8px;">Rule 3</td>
            <td style="border:1px solid #333; padding:8px;">Dimensions differ and none is 1</td>
            <td style="border:1px solid #333; padding:8px;">Error occurs</td>
        </tr>
    </tbody>
</table>

In [7]:
# diff shape
import numpy as np
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [6]:
print(b)

[[0 1 2]]


In [8]:
print(a+b)

[[0 2 4]
 [3 5 7]]


In [9]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)
print(a) # 2 D

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
print(b) # 1 D

[0 1 2]


In [11]:
print(a+b) # Arthematic Operation

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [12]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)
print(a)
print(b)
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [13]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)
print(a)
print(b)
print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [14]:
a = np.arange(3).reshape(2,3)
b = np.arange(3).reshape(3,2)
print(a)
print(b)
print(a+b)

ValueError: cannot reshape array of size 3 into shape (2,3)