## Operations

In [2]:
import numpy as np

In [4]:
z1 = np.arange(12).reshape(3,4)
z2 = np.arange(12,24).reshape(3,4)
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## scalar operations

Scalar operations on Numpy arrays include performing addition or subtraction, or multiplication
on each element of a Numpy array

<table style="width:80%; font-size:14px; border-collapse:collapse; margin:auto; text-align:center;">
    <thead>
        <tr style="background-color:#f2f2f2;">
            <th style="color:purple; border:1px solid #333; padding:10px;">Operation</th>
            <th style="color:purple; border:1px solid #333; padding:10px;">Example</th>
            <th style="color:purple; border:1px solid #333; padding:10px;">Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="border:1px solid #333; padding:8px;">Addition</td>
            <td style="border:1px solid #333; padding:8px;">arr + 5</td>
            <td style="border:1px solid #333; padding:8px;">Adds scalar to each element</td>
        </tr>
        <tr>
            <td style="border:1px solid #333; padding:8px;">Subtraction</td>
            <td style="border:1px solid #333; padding:8px;">arr - 2</td>
            <td style="border:1px solid #333; padding:8px;">Subtracts scalar from each element</td>
        </tr>
        <tr>
            <td style="border:1px solid #333; padding:8px;">Multiplication</td>
            <td style="border:1px solid #333; padding:8px;">arr * 3</td>
            <td style="border:1px solid #333; padding:8px;">Multiplies each element</td>
        </tr>
        <tr>
            <td style="border:1px solid #333; padding:8px;">Division</td>
            <td style="border:1px solid #333; padding:8px;">arr / 2</td>
            <td style="border:1px solid #333; padding:8px;">Divides each element</td>
        </tr>
        <tr>
            <td style="border:1px solid #333; padding:8px;">Power</td>
            <td style="border:1px solid #333; padding:8px;">arr ** 2</td>
            <td style="border:1px solid #333; padding:8px;">Squares each element</td>
        </tr>
        <tr>
            <td style="border:1px solid #333; padding:8px;">Modulus</td>
            <td style="border:1px solid #333; padding:8px;">arr % 2</td>
            <td style="border:1px solid #333; padding:8px;">Returns remainder</td>
        </tr>
    </tbody>
</table>

In [6]:
print(f"Addition with scalar {z1+2}")
print(f"Substraction with scalar {z1-2}")
print(f"Multplication with scalar {z1*2}")
print(f"Division with scalar {z1 / 2}")
print(f"Floor division with scalar {z1 // 2}")
print(f"Exponential with scalar {z1 ** 2}")
print(f"Remainder with scalar {z1 % 2}")

Addition with scalar [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
Substraction with scalar [[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
Multplication with scalar [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
Division with scalar [[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
Floor division with scalar [[0 0 1 1]
 [2 2 3 3]
 [4 4 5 5]]
Exponential with scalar [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
Remainder with scalar [[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


## relational Operators

The relational operators are also known as comparison operators, their main function is to
return either a true or false based on the value of operands.

In [7]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
z1 > 2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [10]:
z1 < 2

array([[ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

## Vector Operation
We can apply on both numpy array

In [11]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
z1 + z2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [15]:
z1 - z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [16]:
z1 * z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [17]:
z1 / z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

## Array Functions

In [29]:
k1 = np.random.random((3,3))
k1 = np.round(k1*100)
k1

array([[ 16.,  16.,  38.],
       [ 53.,  77.,  38.],
       [100.,  30.,  78.]])

In [33]:
np.max(k1)

np.float64(100.0)

In [34]:
np.min(k1)

np.float64(16.0)

In [37]:
# if we want maximum of every row
np.max(k1,axis=1)

array([ 38.,  77., 100.])

In [38]:
# if we want maximum of every column
np.max(k1,axis=0)

array([100.,  77.,  78.])

In [39]:
# if we want maximum of every column
np.min(k1,axis=0)

array([16., 16., 38.])

In [40]:
# if we want maximum of every row
np.min(k1,axis=1)

array([16., 38., 30.])

In [51]:
k1 = np.random.randint(1,5,(2,3))
k1

array([[2, 3, 3],
       [3, 2, 2]])

In [52]:
# product of every column
np.prod(k1, axis = 0)

array([6, 6, 6])

In [53]:
# product of every column
np.prod(k1, axis = 1)

array([18, 12])

## Statistics related fuctions

In [58]:
k1

array([[2, 3, 3],
       [3, 2, 2]])

In [61]:
np.mean(k1)

np.float64(2.5)

In [62]:
np.median(k1)

np.float64(2.5)

In [64]:
np.std(k1)

np.float64(0.5)

In [65]:
np.var(k1)

np.float64(0.25)

## Trignometry Functions

In [67]:
np.sin(k1)

array([[0.90929743, 0.14112001, 0.14112001],
       [0.14112001, 0.90929743, 0.90929743]])

In [68]:
np.cos(k1)

array([[-0.41614684, -0.9899925 , -0.9899925 ],
       [-0.9899925 , -0.41614684, -0.41614684]])

In [69]:
np.tan(k1)

array([[-2.18503986, -0.14254654, -0.14254654],
       [-0.14254654, -2.18503986, -2.18503986]])

## dot product
The numpy module of Python provides a function to perform the dot product of two arrays.

In [70]:
k1

array([[2, 3, 3],
       [3, 2, 2]])

In [77]:
k2 = np.random.randint(1,5,(3,2))
k2

array([[3, 3],
       [4, 3],
       [2, 1]])

In [78]:
k3 = np.dot(k1,k2)
k3

array([[24, 18],
       [21, 17]])

## Log and Exponents

In [79]:
np.exp(k1)

array([[ 7.3890561 , 20.08553692, 20.08553692],
       [20.08553692,  7.3890561 ,  7.3890561 ]])

In [80]:
np.log(k1)

array([[0.69314718, 1.09861229, 1.09861229],
       [1.09861229, 0.69314718, 0.69314718]])

## Iteration

In [81]:
## Looping on 2D array

for i in k1:
    print(i) # prints rows

[2 3 3]
[3 2 2]


## Reshaping

Transpose ---> Converts rows in to clumns ad columns into rows

In [82]:
k1

array([[2, 3, 3],
       [3, 2, 2]])

In [83]:
k2

array([[3, 3],
       [4, 3],
       [2, 1]])

In [84]:
np.transpose(k2)

array([[3, 4, 2],
       [3, 3, 1]])

In [85]:
# Another method
k2.T

array([[3, 4, 2],
       [3, 3, 1]])

In [87]:
# Ravel : Converting any dimensions to 1D
k2.ravel()

array([3, 3, 4, 3, 2, 1])

## Stacking
Stacking is the concept of joining arrays in NumPy. Arrays having the same dimensions can be
stacked

In [88]:
k1

array([[2, 3, 3],
       [3, 2, 2]])

In [99]:
k2 = k2.T
k2

array([[3, 4, 2],
       [3, 3, 1]])

In [100]:
np.hstack((k1,k2))

array([[2, 3, 3, 3, 4, 2],
       [3, 2, 2, 3, 3, 1]])

In [101]:
np.vstack((k1,k2))

array([[2, 3, 3],
       [3, 2, 2],
       [3, 4, 2],
       [3, 3, 1]])

## Splitting
its opposite of Stacking .

In [108]:
np.split(k1,2)

[array([[2, 3, 3]]), array([[3, 2, 2]])]

In [113]:
k1
np.hsplit(k1,3)

[array([[2],
        [3]]),
 array([[3],
        [2]]),
 array([[3],
        [2]])]

In [118]:
k1
np.vsplit(k1,2)

[array([[2, 3, 3]]), array([[3, 2, 2]])]

## Operations

In [16]:
# Creating arrays
a = np.array([1, 2, 3])
print(a)
# Creating arrays with a range of values evenly spaced
b = np.arange(0,10,3)
print(b)
# Creating arrays filled with zeros
c = np.zeros((2,3))
print(c)
# Creating arrays filled with zeros dtype int
d = np.zeros((2,3), dtype=int)
print(d)
# Creating arrays filled with ones
e = np.ones((2,3))
print(e)
# Creating arrays filled with ones dtype int
f = np.ones((2,3), dtype=int)
print(f)
# Creating identity matrix
g = np.eye(4,dtype=int)
print(g)

[1 2 3]
[0 3 6 9]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [20]:
# Array Manipulation

# Reshaping arrays
h = np.array([1, 2, 3, 4, 5, 6])
h_reshaped = h.reshape(2, 3)
print(h_reshaped)

h_reshaped_2 = h.reshape(3, 2)
print(h_reshaped_2)

# Flattening arrays used in CNN maxpooling layers
h_flattened = h_reshaped.flatten()
print(h_flattened)

# raveling arrays
h_raveled = h_reshaped.ravel()
print(h_raveled)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [23]:
# Transposing arrays

i = np.array([[1, 2, 3], [4, 5, 6]])
i_transposed = i.T
print(i_transposed)

#vstack and hstack
j = np.array([1, 2, 3])
k = np.array([4, 5, 6])
j_vstacked = np.vstack((j, k))
print(j_vstacked) 

j_hstacked = np.hstack((j, k))
print(j_hstacked)

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [29]:
## Mathematical Operations

l = np.array([1, 2, 3])
m = np.array([4, 5, 6]) 

# Element-wise addition
add = l + m
print(add)

# Element-wise subtraction
subtract = l - m
print(subtract)

# Element-wise multiplication
multiply = l * m
print(multiply) 

# power
power = l ** 2
print(power)

# Square root
sqrt = np.sqrt(l)
print(sqrt)

# dot product
dot_product = np.dot(l, m)
print(dot_product)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]
32


In [33]:
# Statistical operations

n = np.array([1, 2, 3, 4, 5])   
# Mean
mean = np.mean(n)
print(mean)
# Median
median = np.median(n)
print(median)
# Standard deviation
std_dev = np.std(n)
print(std_dev)
# Variance
variance = np.var(n)
print(variance)

# Minimum and maximum
min_value = np.min(n)
print(min_value)
max_value = np.max(n)
print(max_value)

3.0
3.0
1.4142135623730951
2.0
1
5


In [35]:
# linear algebra operations 
o = np.array([[1, 2], [3, 4]])
p = np.array([[5, 6], [7, 8]])
# Matrix multiplication
matrix_product = np.dot(o, p)
print(matrix_product)
   

[[19 22]
 [43 50]]


In [36]:
# Random Samling
# Random sampling from a normal distribution
random_normal = np.random.normal(loc=0, scale=1, size=(3, 3))
print(random_normal)

[[ 0.87077146  0.34123237  0.29082825]
 [ 1.15445314 -1.11507263 -0.04387856]
 [ 0.50131772 -2.02378595 -0.53454757]]


In [41]:
# seeding random number generator for reproducibility

# Stop to generate the same random numbers every time we run the code
np.random.seed(42) # Seed helps to stop generating new numbers every time we run the code
random_numbers = np.random.rand(5)
print(random_numbers)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [44]:
# linalg operations
array_a = np.array([[1, 2], [3, 4]])
linalg_inv = np.linalg.inv(array_a)
print(linalg_inv)

np.linalg.det(array_a)

np.linalg.eig(array_a)

[[-2.   1. ]
 [ 1.5 -0.5]]


EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

## Working with Missing Values

In [130]:
# Working with missing values -> np.nan
S = np.array([1,2,3,4,np.nan,6])
S

array([ 1.,  2.,  3.,  4., nan,  6.])

In [131]:
np.isnan(S)

array([False, False, False, False,  True, False])

In [132]:
S[~np.isnan(S)]

array([1., 2., 3., 4., 6.])

In [134]:
S[np.isnan(S)]

array([nan])